package UAP;

/*
 * To change this license header, choose License Headeresult in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
import UAP.koneksi;
import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;


public class homeAdmin extends javax.swing.JFrame {
    private Statement state;
    private DefaultTableModel dataTabel;
    private Connection conn;
    private String sql;
    private ResultSet result;



    /**
     * Creates new form homeAdmin
     */
    public String dateChooser;
    
    public homeAdmin() throws SQLException {
        initComponents();
        setLocationRelativeTo(this);
        setJam();
        tampil();
        del();
        validasi.setVisible(false);

    }
    public void del(){
        idBuku_field.setEnabled(true);
        idBuku_field.setText("");
        judul_field.setText("");
        penulis_field.setText("");
        kategoriComboBox.setSelectedItem("");
        saveButton.setText("Tambah");
        keluarButton.setText("Keluar");
    }
    public void tampil() {
        dataTabel = new DefaultTableModel();
        dataTabel.addColumn("ID Buku");
        dataTabel.addColumn("Judul");
        dataTabel.addColumn("Penulis");
        dataTabel.addColumn("Kategori");
        tabelDatabuku.setModel(dataTabel);
        try{
            Statement state = (Statement) koneksi.getkoneksi().createStatement();
            ResultSet result = state.executeQuery("SELECT * FROM tabel_databuku");
            while (result.next()){
                dataTabel.addRow(new Object[]{
                    result.getString("idBuku"), result.getString("judul"), result.getString("penulis"), result.getString("kategori")});
                tabelDatabuku.setModel(dataTabel);    
            }

        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }
    public void tampilPeminjam() {
        
        dataTabel = new DefaultTableModel();
        dataTabel.addColumn("No.Induk");
        dataTabel.addColumn("Nama");
        dataTabel.addColumn("Alamat");
        dataTabel.addColumn("Kelas");
        dataTabel.addColumn("Kode Buku");
        dataTabel.addColumn("Tgl Pinjam");
        dataTabel.addColumn("Tgl Kembali");
        tabelPeminjambuku.setModel(dataTabel);
        try{
            Statement state = (Statement) koneksi.getkoneksi().createStatement();
            ResultSet result = state.executeQuery("select * from `tabel_datapinjam`");
            while (result.next()){
                dataTabel.addRow(new Object[]{
                    result.getString("noInduk"), result.getString("nama"), result.getString("alamat"), result.getString("kelas"), result.getString("kodeBuku"),
                 result.getString("tanggalPinjam"), result.getString("tanggalKembali")});
                
            }
            tabelPeminjambuku.setModel(dataTabel);
        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }
    public final void setJam(){
ActionListener taskPerformer = new ActionListener() {

            @Override
public void actionPerformed(ActionEvent evt) {
String nol_jam = "", nol_menit = "",nol_detik = "";

java.util.Date dateTime = new java.util.Date();
int nilai_jam = dateTime.getHours();
int nilai_menit = dateTime.getMinutes();
int nilai_detik = dateTime.getSeconds();

if(nilai_jam <= 9) nol_jam= "0";
if(nilai_menit <= 9) nol_menit= "0";
if(nilai_detik <= 9) nol_detik= "0";

String jam = nol_jam + Integer.toString(nilai_jam);
String menit = nol_menit + Integer.toString(nilai_menit);
String detik = nol_detik + Integer.toString(nilai_detik);

labelJam.setText(jam+":"+menit+":"+detik+"");
}
};
new Timer(1000, taskPerformer).start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idBuku_field = new javax.swing.JTextField();
        judul_field = new javax.swing.JTextField();
        penulis_field = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        keluarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDatabuku = new javax.swing.JTable();
        validasi = new javax.swing.JLabel();
        kategoriComboBox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPeminjambuku = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelJam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 204, 204));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 153));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel2.setText("Data buku");

        jLabel3.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Kode Buku");

        jLabel4.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Judul");

        jLabel5.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Penulis");

        jLabel6.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Kategori");

        idBuku_field.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N

        judul_field.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N

        penulis_field.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N

        saveButton.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        saveButton.setText("Tambah");
        saveButton.setPreferredSize(new java.awt.Dimension(57, 23));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        hapusButton.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        hapusButton.setText("Hapus");
        hapusButton.setPreferredSize(new java.awt.Dimension(83, 27));
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        keluarButton.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        keluarButton.setText("Keluar");
        keluarButton.setPreferredSize(new java.awt.Dimension(83, 27));
        keluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarButtonActionPerformed(evt);
            }
        });

        tabelDatabuku.setFont(new java.awt.Font("Square721 BT", 0, 12)); // NOI18N
        tabelDatabuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelDatabuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDatabukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDatabuku);

        validasi.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        validasi.setForeground(new java.awt.Color(255, 0, 51));
        validasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        validasi.setText("pesan");
        validasi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        kategoriComboBox.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        kategoriComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pengetahuan", "Fiksi", "Novel" }));
        kategoriComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(validasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(keluarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(judul_field)
                                            .addComponent(idBuku_field)
                                            .addComponent(penulis_field)
                                            .addComponent(kategoriComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(5, 5, 5)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(validasi)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(idBuku_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(judul_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(penulis_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kategoriComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(keluarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Buku", jPanel2);

        tabelPeminjambuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tabelPeminjambuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPeminjambukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPeminjambuku);

        jLabel7.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel7.setText("DAFTAR PEMINJAM BUKU");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel7)
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Peminjam", jPanel3);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Square721 BT", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\KULIAH\\UAP\\logo.png")); // NOI18N
        jLabel1.setText("|Perpustakaan MAN 5 Bojonegoro");

        labelJam.setFont(new java.awt.Font("Square721 BT", 1, 18)); // NOI18N
        labelJam.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelJam, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelJam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Data Buku");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (idBuku_field.getText().equals("")||judul_field.getText().equals("")||penulis_field.getText().equals("")){
            validasi.setText("*Masih ada data yang belum diisi");
            validasi.setVisible(true);
        }else if(saveButton.getText().equals("Tambah")){
            try{
                Statement state = (Statement) koneksi.getkoneksi().createStatement();
                state.executeUpdate("insert into tabel_databuku VALUES"+ "('" 
                        + idBuku_field.getText() + "','" 
                        + judul_field.getText() + "','" 
                        + penulis_field.getText() + "','"
                        + kategoriComboBox.getSelectedItem().toString()+ "');");
                state.close();
                JOptionPane.showMessageDialog(null, "Data berhasil ditambah");
                del();
                tampil();
            }catch (Exception ex) {
                Logger.getLogger(homeAdmin.class.getName()).log(Level.SEVERE, 
                        null, ex);
                validasi.setText("*ID buku tidak boleh sama!");
                validasi.setVisible(true);
            }
            tampil();

        }else {
            try {   
                Statement state = (Statement) koneksi.getkoneksi().
                        createStatement();
                state.executeUpdate("UPDATE tabel_databuku SET idBuku = '"
                        + idBuku_field.getText()
                        +"',"
                        + " `judul` = '"+ judul_field.getText()
                        +"',"
                        + " `penulis` = '"+ penulis_field.getText()
                        +"',"
                        + " `kategori` = '"+kategoriComboBox.getSelectedItem().toString()
                        +"'WHERE tabel_databuku.idBuku = '"+ idBuku_field.getText()+"'");
                tampil();
                del();
                JOptionPane.showMessageDialog(null, "Data Berhasi di edit");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Data gagal di edit");
                Logger.getLogger(homeAdmin.class.getName()).log(Level.SEVERE, 
                        null, ex);
            }
        }    
    }//GEN-LAST:event_saveButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        // TODO add your handling code here:
        int row = tabelDatabuku.getSelectedRow();
        if (row < 0){
            validasi.setText("Pilih data terlebih dahulu");
            validasi.setVisible(true);
        }else{
            String kode = idBuku_field.getText();
            try(Statement state = (Statement) koneksi.getkoneksi().createStatement()){
                state.executeUpdate("DELETE FROM tabel_databuku WHERE tabel_databuku."+"idBuku =('"+kode+"');");
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                state.close();
                idBuku_field.setText("");
                judul_field.setText("");
                penulis_field.setText("");
                tampil();
            }catch (Exception ex) {
            Logger.getLogger(homeAdmin.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Data gagal Dihapus");
        }
            
        }
        
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void keluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarButtonActionPerformed
        // TODO add your handling code here:
        if (keluarButton.getText().equals("Keluar")){
            int confirm = JOptionPane.showConfirmDialog(null, "Apakah anda yakin?", "Yakin?", JOptionPane.YES_NO_OPTION);
            
            if (confirm == JOptionPane.YES_OPTION){
                loginAdmin l = new loginAdmin();
                l.setVisible(true);
                this.dispose();
            }else{
                tampil();
            }
                
            
        }else{
              tampil(); 
              del();
            }
        
    }//GEN-LAST:event_keluarButtonActionPerformed

    private void tabelDatabukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDatabukuMouseClicked
        saveButton.setText("Edit");
        keluarButton.setText("Batal");      
        int baris =tabelDatabuku.rowAtPoint(evt.getPoint());
        String id =tabelDatabuku.getValueAt(baris, 0).toString();
        idBuku_field.setText(id);
        String judul = tabelDatabuku.getValueAt(baris,1).toString();
        judul_field.setText(judul);
        String penulis = tabelDatabuku.getValueAt(baris,2).toString();
        penulis_field.setText(penulis);
        if(tabelDatabuku.getValueAt(tabelDatabuku.getSelectedRow(),3).toString().
                equals("Pengetahuan")){
            kategoriComboBox.setSelectedIndex(0);
        }else if(tabelDatabuku.getValueAt(tabelDatabuku.getSelectedRow(),3).toString().
                equals("Fiksi")){
            kategoriComboBox.setSelectedIndex(1);
        }else if(tabelDatabuku.getValueAt(tabelDatabuku.getSelectedRow(),3).toString().
                equals("Novel")){
            kategoriComboBox.setSelectedIndex(2);
        }

    }//GEN-LAST:event_tabelDatabukuMouseClicked

    private void kategoriComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kategoriComboBoxActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        tampilPeminjam();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void tabelPeminjambukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPeminjambukuMouseClicked

    }//GEN-LAST:event_tabelPeminjambukuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new homeAdmin().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(homeAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapusButton;
    private javax.swing.JTextField idBuku_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField judul_field;
    private javax.swing.JComboBox<String> kategoriComboBox;
    private javax.swing.JButton keluarButton;
    private javax.swing.JLabel labelJam;
    private javax.swing.JTextField penulis_field;
    private javax.swing.JButton saveButton;
    private javax.swing.JTable tabelDatabuku;
    private javax.swing.JTable tabelPeminjambuku;
    private javax.swing.JLabel validasi;
    // End of variables declaration//GEN-END:variables

    
}
